import {
  Activity,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Bot,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock,
  Download,
  ExternalLink,
  File,
  FileText,
  Folder,
  FolderPlus,
  GitFork,
  Globe2,
  Info,
  Keyboard,
  Map,
  Maximize2,
  MessageSquare,
  MessageSquarePlus,
  Minus,
  MoreHorizontal,
  PanelLeft,
  PanelRight,
  Paperclip,
  Plug,
  Plus,
  RefreshCw,
  Search,
  Server,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Square,
  Sun,
  Workflow,
  X,
  type LucideIcon,
} from "lucide-react";

/*
 * The renderer uses Lucide for chrome and composer controls. Keeping the
 * mapping in one file lets the AEGIS callbacks stay local while the visible
 * glyphs use one consistent icon family and stroke geometry.
 */
const icons: Record<string, LucideIcon> = {
  plus: Plus,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  sidebar: PanelLeft,
  search: Search,
  sessions: MessageSquare,
  folder: Folder,
  "new-project": FolderPlus,
  branch: GitFork,
  extensions: Workflow,
  settings: Settings,
  panel: PanelRight,
  more: MoreHorizontal,
  spark: Sparkles,
  attach: Paperclip,
  "arrow-up": ArrowUp,
  check: Check,
  activity: Activity,
  map: Map,
  files: FileText,
  circle: Circle,
  external: ExternalLink,
  sun: Sun,
  bell: Bell,
  plug: Plug,
  "new-chat": MessageSquarePlus,
  shield: Shield,
  sliders: SlidersHorizontal,
  bot: Bot,
  keyboard: Keyboard,
  file: File,
  server: Server,
  globe: Globe2,
  download: Download,
  info: Info,
  refresh: RefreshCw,
  sort: ArrowUpDown,
  clock: Clock,
  minimize: Minus,
  maximize: Square,
  restore: Maximize2,
  close: X,
};

export function CapabilityIcon({ name, size = 16 }: { name: string; size?: number }) {
  const Icon = icons[name] ?? Circle;
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true" />;
}
