"""
AEGIS-COGNITION: Cryptographically-verified AI agent harness.

Drop-in developer experience:
    from aegis_cognition import Agent
    agent = Agent(task="Find trending repos on GitHub")
    result = agent.run()

For quick setup:
    pip install aegis-cognition
    aegis init
    aegis run "Hello world"
"""

from __future__ import annotations

__version__ = "0.1.0"
__all__ = [
    "AGENT_COORDINATION_SCHEMA_V1",
    "AGENT_GRAPH_SCHEMA_V1",
    "AGENT_MESSAGE_SCHEMA_V1",
    "AGENT_PLAN_SCHEMA_V1",
    "AGENT_RESULT_SCHEMA_V1",
    "CODE_REUSE_SCHEMA_V1",
    "DEFAULT_GOAL_CONTRACT_LIMITS",
    "DEFAULT_UNIT_REGISTRY",
    "EVIDENCE_CLASSES",
    "EVIDENCE_STATUSES",
    "REDDIT_RSS_HOST",
    "RESEARCH_ADAPTER_SCHEMA_V1",
    "VISION_ADAPTER_SCHEMA_V1",
    "AcceptancePredicate",
    "AdaptiveController",
    "AdaptiveMeasurementResult",
    "AdaptiveMeasurementSession",
    "AdaptiveMeasurementSpec",
    "Agent",
    "AgentArtifactRef",
    "AgentClaim",
    "AgentCoordinationError",
    "AgentHandler",
    "AgentImplementationPacket",
    "AgentMessage",
    "AgentPlanProposal",
    "AgentResultPacket",
    "AgentSupervisor",
    "AgentSupervisorResult",
    "AgentTaskBlueprint",
    "AgentTaskContext",
    "AgentTaskSpec",
    "AnalyticPredictionModel",
    "AnchorCandidate",
    "AnchorObservation",
    "AnchorSelectionPlan",
    "ArtifactReference",
    "AuthorityMode",
    "BenchmarkProtocolV2",
    "BenchmarkResultV2",
    "BenchmarkTrialRecord",
    "BrowserCaptureProvider",
    "BrowserObserverView",
    "CalibrationResult",
    "CodeReuseAssessment",
    "CodeReuseCandidate",
    "CodeReuseError",
    "CodeReusePolicy",
    "CodeReuseReceipt",
    "ContractValidationError",
    "CorrelationContext",
    "CoverageVector",
    "DevelopmentVerificationSession",
    "ElectricalSignalCell",
    "ElectricalSignalResult",
    "ElectricalSignalSpec",
    "EnvironmentFingerprint",
    "EvidenceLedger",
    "EvidenceLedgerEntry",
    "EvidencePolicy",
    "ExecutionCellBinding",
    "ExecutionCellRegistry",
    "ExecutionReceipt",
    "ExternalSideEffectLease",
    "GoalBudgetContract",
    "GoalContract",
    "GoalContractError",
    "GoalContractLimits",
    "GoalLifecycle",
    "GoalProgress",
    "GoalVerdict",
    "GoalVerification",
    "HardwareCapabilityVector",
    "Lab",
    "LabApplication",
    "LabBudget",
    "LabDossier",
    "LabMissionSpec",
    "LabPolicy",
    "LabSession",
    "ODEIntegrationResult",
    "PhysicalConstraint",
    "PredictionResult",
    "ProcessExecutionCell",
    "ProjectProfile",
    "PublicResearchRouter",
    "RedditRssQueryProvider",
    "ReplayWriterLease",
    "ResearchAdapterError",
    "ResearchSourceUnavailable",
    "RuntimeMetrics",
    "RuntimeTelemetry",
    "SearchOperation",
    "SearchProgram",
    "SearchProgramExecutor",
    "SimulationCell",
    "SimulationEvidence",
    "SimulationSpec",
    "SkillAdmission",
    "SkillAdmissionError",
    "SkillExecutionReceipt",
    "SkillManifest",
    "SkillRegistry",
    "StaleGoalGeneration",
    "TargetDescriptor",
    "TestChangeProposal",
    "TestDescriptor",
    "UnitDefinition",
    "UnitRegistry",
    "VerificationAssessment",
    "VerificationEvent",
    "VerificationFacade",
    "VerificationPlan",
    "VerificationRequirement",
    "VerificationSessionError",
    "VisionAdapterError",
    "VisionImage",
    "VisionInvoker",
    "VisionObservation",
    "VisionObservationProvider",
    "WorkloadSignature",
    "XAppOnlyQueryProvider",
    "admit_cooperative_placement",
    "assess_code_reuse",
    "build_browser_vision_handler",
    "build_local_reuse_candidate",
    "build_model_subagent_handler",
    "build_public_research_handler",
    "build_root_synthesizer",
    "build_vision_subagent_handler",
    "calibrate_placement",
    "calibrate_simulation",
    "cooperative_placement_preview",
    "cooperative_placement_preview_with_calibration",
    "evaluate_adaptive_measurement",
    "evaluate_benchmark",
    "execution_lanes",
    "external_side_effect_key",
    "finish_runtime_lease",
    "hardware_profile",
    "materialize_exact",
    "observe_runtime_resources",
    "parse_agent_plan",
    "placement_capabilities",
    "placement_plan",
    "placement_plan_with_calibration",
    "placement_resource_request",
    "predict_cross_hardware",
    "release_cooperative_placement",
    "resource_contract_version",
    "resource_usage_sample",
    "run",
    "select_anchor_plan",
    "submit_placement_task",
    "submit_runtime_task",
    "validate_agent_graph",
    "validate_agent_graph_locally",
    "version",
]

# Re-export the Friendly Gateway Agent with simple name
from .agent import Agent
from .agent import run as run
from .subagents import (
    AGENT_COORDINATION_SCHEMA_V1,
    AGENT_GRAPH_SCHEMA_V1,
    AGENT_MESSAGE_SCHEMA_V1,
    AGENT_PLAN_SCHEMA_V1,
    AGENT_RESULT_SCHEMA_V1,
    AgentArtifactRef,
    AgentClaim,
    AgentCoordinationError,
    AgentHandler,
    AgentMessage,
    AgentPlanProposal,
    AgentResultPacket,
    AgentSupervisor,
    AgentSupervisorResult,
    AgentTaskBlueprint,
    AgentTaskContext,
    AgentTaskSpec,
    build_model_subagent_handler,
    build_root_synthesizer,
    parse_agent_plan,
    validate_agent_graph,
    validate_agent_graph_locally,
)
from .benchmark import (
    BenchmarkProtocolV2,
    BenchmarkResultV2,
    BenchmarkTrialRecord,
    EnvironmentFingerprint,
    evaluate_benchmark,
)
from .aese import (
    AdaptiveMeasurementResult,
    AdaptiveMeasurementSpec,
    AdaptiveMeasurementSession,
    AnchorCandidate,
    AnchorSelectionPlan,
    AnchorObservation,
    AnalyticPredictionModel,
    EVIDENCE_CLASSES,
    EVIDENCE_STATUSES,
    EvidenceLedger,
    EvidenceLedgerEntry,
    HardwareCapabilityVector,
    PredictionResult,
    CoverageVector,
    SimulationEvidence,
    WorkloadSignature,
    evaluate_adaptive_measurement,
    predict_cross_hardware,
    select_anchor_plan,
)
from .lab import (
    DEFAULT_UNIT_REGISTRY,
    AdaptiveController,
    AuthorityMode,
    CalibrationResult,
    ElectricalSignalCell,
    ElectricalSignalResult,
    ElectricalSignalSpec,
    ExecutionCellBinding,
    ExecutionCellRegistry,
    Lab,
    LabApplication,
    LabBudget,
    LabDossier,
    LabMissionSpec,
    LabPolicy,
    LabSession,
    ODEIntegrationResult,
    BrowserObserverView,
    PhysicalConstraint,
    ProcessExecutionCell,
    ExternalSideEffectLease,
    ReplayWriterLease,
    SearchOperation,
    SearchProgram,
    SearchProgramExecutor,
    SkillAdmission,
    SkillAdmissionError,
    SkillExecutionReceipt,
    SkillManifest,
    SkillRegistry,
    SimulationCell,
    SimulationSpec,
    UnitDefinition,
    UnitRegistry,
    calibrate_simulation,
)
from .research_adapters import (
    REDDIT_RSS_HOST,
    RESEARCH_ADAPTER_SCHEMA_V1,
    PublicResearchRouter,
    RedditRssQueryProvider,
    ResearchAdapterError,
    ResearchSourceUnavailable,
    XAppOnlyQueryProvider,
    build_public_research_handler,
)
from .code_reuse import (
    CODE_REUSE_SCHEMA_V1,
    CodeReuseAssessment,
    CodeReuseCandidate,
    CodeReuseError,
    CodeReusePolicy,
    CodeReuseReceipt,
    assess_code_reuse,
    build_local_reuse_candidate,
    materialize_exact,
)
from .vision_adapters import (
    BrowserCaptureProvider,
    VISION_ADAPTER_SCHEMA_V1,
    VisionAdapterError,
    VisionImage,
    VisionInvoker,
    VisionObservation,
    VisionObservationProvider,
    build_browser_vision_handler,
    build_vision_subagent_handler,
)
from .goal_contract import (
    AcceptancePredicate,
    EvidencePolicy,
    GoalBudgetContract,
    GoalContract,
    GoalContractError,
    GoalContractLimits,
    DEFAULT_GOAL_CONTRACT_LIMITS,
    GoalLifecycle,
    GoalProgress,
    GoalVerification,
    GoalVerdict,
    StaleGoalGeneration,
    TargetDescriptor,
    external_side_effect_key,
)
from .verification import (
    AgentImplementationPacket,
    ArtifactReference,
    ContractValidationError,
    DevelopmentVerificationSession,
    ExecutionReceipt,
    ProjectProfile,
    TestChangeProposal,
    TestDescriptor,
    VerificationAssessment,
    VerificationEvent,
    VerificationFacade,
    VerificationPlan,
    VerificationRequirement,
    VerificationSessionError,
)
from .metrics import RuntimeMetrics
from .observability import CorrelationContext, RuntimeTelemetry
from .runtime import (
    admit_cooperative_placement,
    calibrate_placement,
    cooperative_placement_preview,
    cooperative_placement_preview_with_calibration,
    execution_lanes,
    finish_runtime_lease,
    hardware_profile,
    observe_runtime_resources,
    placement_capabilities,
    placement_plan,
    placement_plan_with_calibration,
    placement_resource_request,
    resource_contract_version,
    resource_usage_sample,
    release_cooperative_placement,
    submit_placement_task,
    submit_runtime_task,
)


def version() -> str:
    """Return AEGIS-COGNITION version."""
    return __version__
