"""
AEGIS-COGNITION: Cryptographically-verified AI agent harness.

Drop-in developer experience:
    from aegis_cognition import Agent
    agent = Agent(task="Find trending repos on GitHub")
    result = agent.run()

For quick setup:
    pip install aegis-cognition
    aegis init
    aegis run "Hello world"
"""

from __future__ import annotations

__version__ = "0.1.0"
__all__ = [
    "DEFAULT_GOAL_CONTRACT_LIMITS",
    "DEFAULT_UNIT_REGISTRY",
    "EVIDENCE_CLASSES",
    "EVIDENCE_STATUSES",
    "AcceptancePredicate",
    "AdaptiveController",
    "AdaptiveMeasurementResult",
    "AdaptiveMeasurementSession",
    "AdaptiveMeasurementSpec",
    "Agent",
    "AgentImplementationPacket",
    "AnalyticPredictionModel",
    "AnchorCandidate",
    "AnchorObservation",
    "AnchorSelectionPlan",
    "ArtifactReference",
    "AuthorityMode",
    "BenchmarkProtocolV2",
    "BenchmarkResultV2",
    "BenchmarkTrialRecord",
    "BrowserObserverView",
    "CalibrationResult",
    "ContractValidationError",
    "CorrelationContext",
    "CoverageVector",
    "DevelopmentVerificationSession",
    "ElectricalSignalCell",
    "ElectricalSignalResult",
    "ElectricalSignalSpec",
    "EnvironmentFingerprint",
    "EvidenceLedger",
    "EvidenceLedgerEntry",
    "EvidencePolicy",
    "ExecutionCellBinding",
    "ExecutionCellRegistry",
    "ExecutionReceipt",
    "ExternalSideEffectLease",
    "GoalBudgetContract",
    "GoalContract",
    "GoalContractError",
    "GoalContractLimits",
    "GoalLifecycle",
    "GoalProgress",
    "GoalVerdict",
    "GoalVerification",
    "HardwareCapabilityVector",
    "Lab",
    "LabApplication",
    "LabBudget",
    "LabDossier",
    "LabMissionSpec",
    "LabPolicy",
    "LabSession",
    "ODEIntegrationResult",
    "PhysicalConstraint",
    "PredictionResult",
    "ProcessExecutionCell",
    "ProjectProfile",
    "ReplayWriterLease",
    "RuntimeMetrics",
    "RuntimeTelemetry",
    "SearchOperation",
    "SearchProgram",
    "SearchProgramExecutor",
    "SimulationCell",
    "SimulationEvidence",
    "SimulationSpec",
    "SkillAdmission",
    "SkillAdmissionError",
    "SkillExecutionReceipt",
    "SkillManifest",
    "SkillRegistry",
    "StaleGoalGeneration",
    "TargetDescriptor",
    "TestChangeProposal",
    "TestDescriptor",
    "UnitDefinition",
    "UnitRegistry",
    "VerificationAssessment",
    "VerificationEvent",
    "VerificationFacade",
    "VerificationPlan",
    "VerificationRequirement",
    "VerificationSessionError",
    "WorkloadSignature",
    "admit_cooperative_placement",
    "calibrate_placement",
    "calibrate_simulation",
    "cooperative_placement_preview",
    "cooperative_placement_preview_with_calibration",
    "evaluate_adaptive_measurement",
    "evaluate_benchmark",
    "execution_lanes",
    "external_side_effect_key",
    "finish_runtime_lease",
    "hardware_profile",
    "observe_runtime_resources",
    "placement_capabilities",
    "placement_plan",
    "placement_plan_with_calibration",
    "placement_resource_request",
    "predict_cross_hardware",
    "release_cooperative_placement",
    "resource_contract_version",
    "resource_usage_sample",
    "run",
    "select_anchor_plan",
    "submit_placement_task",
    "submit_runtime_task",
    "version",
]

# Re-export the Friendly Gateway Agent with simple name
from .agent import Agent
from .agent import run as run
from .benchmark import (
    BenchmarkProtocolV2,
    BenchmarkResultV2,
    BenchmarkTrialRecord,
    EnvironmentFingerprint,
    evaluate_benchmark,
)
from .aese import (
    AdaptiveMeasurementResult,
    AdaptiveMeasurementSpec,
    AdaptiveMeasurementSession,
    AnchorCandidate,
    AnchorSelectionPlan,
    AnchorObservation,
    AnalyticPredictionModel,
    EVIDENCE_CLASSES,
    EVIDENCE_STATUSES,
    EvidenceLedger,
    EvidenceLedgerEntry,
    HardwareCapabilityVector,
    PredictionResult,
    CoverageVector,
    SimulationEvidence,
    WorkloadSignature,
    evaluate_adaptive_measurement,
    predict_cross_hardware,
    select_anchor_plan,
)
from .lab import (
    DEFAULT_UNIT_REGISTRY,
    AdaptiveController,
    AuthorityMode,
    CalibrationResult,
    ElectricalSignalCell,
    ElectricalSignalResult,
    ElectricalSignalSpec,
    ExecutionCellBinding,
    ExecutionCellRegistry,
    Lab,
    LabApplication,
    LabBudget,
    LabDossier,
    LabMissionSpec,
    LabPolicy,
    LabSession,
    ODEIntegrationResult,
    BrowserObserverView,
    PhysicalConstraint,
    ProcessExecutionCell,
    ExternalSideEffectLease,
    ReplayWriterLease,
    SearchOperation,
    SearchProgram,
    SearchProgramExecutor,
    SkillAdmission,
    SkillAdmissionError,
    SkillExecutionReceipt,
    SkillManifest,
    SkillRegistry,
    SimulationCell,
    SimulationSpec,
    UnitDefinition,
    UnitRegistry,
    calibrate_simulation,
)
from .goal_contract import (
    AcceptancePredicate,
    EvidencePolicy,
    GoalBudgetContract,
    GoalContract,
    GoalContractError,
    GoalContractLimits,
    DEFAULT_GOAL_CONTRACT_LIMITS,
    GoalLifecycle,
    GoalProgress,
    GoalVerification,
    GoalVerdict,
    StaleGoalGeneration,
    TargetDescriptor,
    external_side_effect_key,
)
from .verification import (
    AgentImplementationPacket,
    ArtifactReference,
    ContractValidationError,
    DevelopmentVerificationSession,
    ExecutionReceipt,
    ProjectProfile,
    TestChangeProposal,
    TestDescriptor,
    VerificationAssessment,
    VerificationEvent,
    VerificationFacade,
    VerificationPlan,
    VerificationRequirement,
    VerificationSessionError,
)
from .metrics import RuntimeMetrics
from .observability import CorrelationContext, RuntimeTelemetry
from .runtime import (
    admit_cooperative_placement,
    calibrate_placement,
    cooperative_placement_preview,
    cooperative_placement_preview_with_calibration,
    execution_lanes,
    finish_runtime_lease,
    hardware_profile,
    observe_runtime_resources,
    placement_capabilities,
    placement_plan,
    placement_plan_with_calibration,
    placement_resource_request,
    resource_contract_version,
    resource_usage_sample,
    release_cooperative_placement,
    submit_placement_task,
    submit_runtime_task,
)


def version() -> str:
    """Return AEGIS-COGNITION version."""
    return __version__
